# Alpine image with python3 installed

FROM alpine:latest
RUN apk update; \
    apk add --update python3; \ 
    pip3 install -U setuptools pip
COPY ./requirements.txt / 
RUN pip3 install -r requirements.txt
