# alpine image with python2 installed
# 2018-04-12

FROM alpine:latest

RUN apk add --update python2-dev py2-pip g++ gcc make libc-dev libffi-dev openssl-dev musl-dev ; \ 
    pip2 install -U setuptools pip
COPY ./requirements.txt / 
RUN pip2 install -r requirements.txt
