# Alpine image with python2 installed

FROM alpine:latest
RUN apk update; \
    apk add --update python py2-pip; \ 
    pip install -U setuptools pip
COPY ./requirements.txt / 
RUN pip install -r requirements.txt
