# Alpine image with ansible installed
# 2018-03-11

FROM alpine:latest
RUN apk add --update gcc make libffi-dev openssl-dev musl-dev python2 python2-dev py2-pip sshpass; \ 
    pip install -U setuptools pip ansible
